### ISSUE TITLE
Your requirements.txt is invalid. Snapshot your logs for details.

### ISSUE THREAD

**Issue by ugaemi** [ugaemi/emariya#5]
`eb deploy`를 할 때 `requirements.txt` 관련 이슈가 생겼다.

**Comment by ugaemi** [comment]
필요없는 라이브러리명을 지우고 `pip freeze > requirements.txt`로 다시 파일을 만들어보았다.
문제없이 잘 실행된다 <퍽 (새로운 이슈 생김;)

**Comment by ugaemi** [comment]
다시 원점으로 돌아왔다.
EB 콘솔에서 로그를 찾아보니 `psycopg` 설치 시에 에러가 난다.

**Comment by ugaemi** [comment]
[Django 애플리케이션을 Elastic Beanstalk에 배포](https://docs.aws.amazon.com/ko_kr/elasticbeanstalk/latest/dg/create-deploy-python-django.html) 도큐먼트를 보는데 python 3.6 플랫폼과 호환되는 최신 장고 버전이 2.1이라 하여 다운그레이드를 하게 되었다.

**Comment by ugaemi** [comment]
```python
Collecting psycopg2==2.8.4 (from -r /opt/python/ondeck/app/requirements.txt (line 14))
    Using cached https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz
      Complete output from command python setup.py egg_info:
      running egg_info
      creating pip-egg-info/psycopg2.egg-info
      writing pip-egg-info/psycopg2.egg-info/PKG-INFO
      writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
      writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
      writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
      /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
        warnings.warn(msg)
      warning: manifest_maker: standard file '-c' not found
      
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <http://initd.org/psycopg/docs/install.html>).
      
      
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g059tlm1/psycopg2/
  You are using pip version 9.0.1, however version 19.3.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  2019-12-12 06:09:32,490 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1 (Executor::NonZeroExitStatus)
```
